<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tbl_1602Q extends Model
{
    protected $connection = 'mysql2';

    protected $fillable = [
        'form_no',
		'company_id',
		'item1',
		'item2',
		'item3',
		'item4',
		'item5',
		'item11',
		'item13',
		'item13A',
		'item14',
		'item15',
		'item16',
		'item17',
		'item18',
		'item19',
		'item20',
		'item21',
		'item22',
		'item23',
		'item24',
		'item25',
		'item26',
		'item27',
		'item28',
		'item_over_remittance',
		'item_sched1_amount1',
		'item_sched1_tax1',
		'item_sched1_amount2',
		'item_sched1_tax2',
		'item_sched1_amount3',
		'item_sched1_tax3',
		'item_sched1_amount4',
		'item_sched1_tax4',
		'item_sched1_amount5',
		'item_sched1_tax5',
		'item_sched1_amount6',
		'item_sched1_tax6',
		'item_sched1_amount7',
		'item_sched1_tax7',
		'item_sched1_amount8',
		'item_sched1_tax8',
		'item_sched1_amount9',
		'item_sched1_tax9',
		'item_sched1_amount10',
		'item_sched1_tax10',
		'item_sched1_amount11',
		'item_sched1_tax11',
		'item_sched1_amount12',
		'item_sched1_tax12',
		'item_sched1_amount13',
		'item_sched1_rate13',
		'item_sched1_tax13',
		'item_sched1_amount14',
		'item_sched1_rate14',
		'item_sched1_tax14',
		'item_sched1_amount15',
		'item_sched1_tax15',
		'item_sched1_total',
		'item_sched2_treaty1',
		'item_sched2_atc1',
		'item_sched2_interest1',
		'item_sched2_rate1',
		'item_sched2_withheld1',
		'item_sched2_treaty2',
		'item_sched2_atc2',
		'item_sched2_interest2',
		'item_sched2_rate2',
		'item_sched2_withheld2',
		'item_sched2_total',
		'item_sched3_PA1',
		'item_sched3_interest1',
		'item_sched3_rate1',
		'item_sched3_withheld1',
		'item_sched3_PA2',
		'item_sched3_interest2',
		'item_sched3_rate2',
		'item_sched3_withheld2',
		'item_sched3_total',
    ];
}
