<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tbl_2550Q extends Model
{
    protected $connection = 'mysql2';

    protected $fillable = [
    				'form_no',
					'company_id',
					'item1A',
					'item1B',
					'item1C',
					'item2',
					'item3A',
					'item3B',
					'item4',
					'item5',
					'item8',
					'item14A',
					'item14B',
					'item15A',
					'item15B',
					'item16A',
					'item16B',
					'item17',
					'item18',
					'item19A',
					'item19B',
					'item20A',
					'item20B',
					'item20C',
					'item20D',
					'item20E',
					'item20F',
					'item21A',
					'item21B',
					'item21C',
					'item21D',
					'item21E',
					'item21F',
					'item21G',
					'item21H',
					'item22I',
					'item21J',
					'item21K',
					'item21L',
					'item21M',
					'item21N',
					'item21O',
					'item21P',
					'item22',
					'item23A',
					'item_total23A',
					'item23B',
					'item_total23B',
					'item23C',
					'item_total23C',
					'item23D',
					'item23E',
					'item23F',
					'item24',
					'item25',
					'item26A',
					'item26B',
					'item26C',
					'item26D',
					'item26E',
					'item26F',
					'item26G',
					'item26H',
					'item27',
					'item28A',
					'item28B',
					'item28C',
					'item28D',
					'item29',
					'item_overpayment',
					'total_amount',
				];
}
