<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class tbl_2200S extends Model
{
    protected $connection = 'mysql2';

    protected $fillable = [
        'form_no',
		'company_id',
		'item1A',
		'item1B',
		'item1C',
		'item2',
		'item3',
		'item10',
		'item12A',
		'item12B',
		'item12C',
		'item13A',
		'item13B',
		'item13C',
		'item14',
		'item14A',
		'item15',
		'item17',
		'item17_others',
		'item18',
		'item19A',
		'item19B',
		'item19C',
		'item20',
		'item21',
		'item22',
		'item23A',
		'item23B',
		'item23C',
		'item23D',
		'item24',
		'item25A',
		'item25B',
		'item25B_penalties',
		'item25C',
		'item26',
		'item_sales1',
		'item_removals1',
		'item_tax1',
		'item_sales2',
		'item_removals2',
		'item_tax2',
		'item_sales3',
		'item_removals3',
		'item_tax3',
		'item_sales4',
		'item_removals4',
		'item_tax4',
		'item_sales5',
		'item_removals5',
		'item_tax5',
		'item_sales6',
		'item_removals6',
		'item_tax6',
		'item_sales7',
		'item_removals7',
		'item_tax7',
		'item_sales8',
		'item_removals8',
		'item_tax8',
		'item_sales9',
		'item_removals9',
		'item_tax9',
		'item_sales10',
		'item_removals10',
		'item_tax10',
    ];
}
